name: WeylModules
version: "Version 2.0"
license: "GPL-2.0-or-later"
date: 2024-02-29
description: |
    for simple simply-connected algebraic groups

authors:
    - name: Stephen Doty
      url: https://doty.math.luc.edu

maintainers:
    - name: Stephen Doty
      url: https://doty.math.luc.edu

GAP: ">= 4.11"

www: https://srdoty.github.io/WeylModulesNew/
readme: README.md
packageinfo: https://srdoty.github.io/WeylModulesNew/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/srdoty/WeylModulesNew/releases/download/vVersion 2.0/WeylModules-Version 2.0.tar.gz

abstract: |

status: other
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    algebraic groups, Weyl modules.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Dot24</span>]   <b class='BibAuthor'>Doty, S.</b>,
     <i class='BibTitle'>WeylModules, for simple simply-connected algebraic groups,
             Version Version 2.0</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://srdoty.github.io/WeylModulesNew/">https://srdoty.github.io/WeylModulesNew/</a></span>.
    </p>
    

bibtex: |
    @misc{ WeylModulesVersion 2.0,
      author =           {Doty, S.},
      title =            {{WeylModules},  for  simple simply-connected algebraic
                          groups, {V}ersion Version 2.0},
      month =            {Feb},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href       {https://srdoty.github.io/WeylModulesNew/}
                          {\texttt{https://srdoty.github.io/}\discretionary
                          {}{}{}\texttt{WeylModulesNew/}}},
      keywords =         {algebraic groups; Weyl modules},
      printedkey =       {Dot24}
    }

